name       : exfatprogs
version    : 1.0.4
release    : 1
source     :
    - https://github.com/exfatprogs/exfatprogs/archive/1.0.4.tar.gz : 3f755d35785a74138348b3a22dfcda5afc8a69e66a6a0c79be48225e6ca321ce
license    : GPL-2.0-or-later
component  : system.utils
summary    : exFAT filesystem userspace utilities
description: |
    exfatprogs are the official userspace utilities that contain all of the standard utilities for creating, fixing and debugging exFAT filesystems in Linux.
replaces   :
    - exfat-utils
setup      : |
    %autogen
build      : |
    %make
install    : |
    %make_install
