name       : exfatprogs
version    : 1.1.0
release    : 2
source     :
    - https://github.com/exfatprogs/exfatprogs/archive/1.1.0.tar.gz : 88c12a2f9cbe4f12129f3b7fa2cd42f24dbed3f579e61bac2ca699ca79fad4e0
license    : GPL-2.0-or-later
component  : system.utils
summary    : exFAT filesystem userspace utilities
description: |
    exfatprogs are the official userspace utilities that contain all of the standard utilities for creating, fixing and debugging exFAT filesystems in Linux.
replaces   :
    - exfat-utils
setup      : |
    %autogen
build      : |
    %make
install    : |
    %make_install
