name       : exfatprogs
version    : 1.1.1
release    : 4
source     :
    - https://github.com/exfatprogs/exfatprogs/archive/refs/tags/1.1.1.tar.gz : 7984d93731066841a93fb3b7397083bffb5a52c5e44165b5caf449954ee984ae
license    : GPL-2.0-or-later
component  : system.utils
summary    : exFAT filesystem userspace utilities
description: |
    exfatprogs are the official userspace utilities that contain all of the standard utilities for creating, fixing and debugging exFAT filesystems in Linux.
replaces   :
    - exfat-utils
setup      : |
    %autogen
build      : |
    %make
install    : |
    %make_install
